### ISSUE TITLE
Support for mobile

### ISSUE THREAD

**Issue by astrodad** [meld-cp/obsidian-encrypt#10]
Hi there! 

I tried to install this on the iOS beta and it says hat the plugin is not supported on mobile. Without having yet looked too deeply, is there some major problem with the plugin that makes it incompatible? Perhaps a library issue? What would it take to make it mobile compatible?

**Comment by meld-cp** [comment]
Hi, yeah, I marked it as desktop only because there wasn't a way for me to test if it would work on mobile, but with the app just around the corner I'll look into it again in the next few days.  Perhaps I'll remove the lock-in to desktop which allows others with access to the app to test and log issues.  Cheers

**Comment by astrodad** [comment]
Thanks! If you need any testing done on the beta let me know.

**Comment by meld-cp** [comment]
Thanks,  I might take you up on that 🙂

**Comment by meld-cp** [comment]
v1.3.3 removes the desktop-only constraint.  See how you get on.  I'll close this issue, but please open another if you find any issues when using the mobile app.  Thanks!
