### ISSUE TITLE
Fingerprint Option 

### ISSUE THREAD

**Issue by mjain234** [meld-cp/obsidian-encrypt#122]
There should be a fingerprint Option for encrypting note which would be much faster instead of typing the password. Will there be in future?

**Comment by meld-cp** [comment]
Hi @mjain234,

I agree, using a fingerprint would be great, but I'm not sure how this would translate to the desktop app which typically don't have fingerprint readers.

Devices without fingerprint readers could fallback to passwords, but then does that mean I need to keep track of 2 encrypted copies of notes (one for fingerprints and the other for a fallback password)?  What happens when you change a note on a device without a fingerprint reader, I need to reecrypt the changes, but now can't use the fingerprint data.

Sounds complicated
