### ISSUE TITLE
decryption failed

### ISSUE THREAD

**Issue by sgab31** [meld-cp/obsidian-encrypt#45]
impossible to decrypt a very important note.
Obsidian responds "decryption failed" even though I am sure of the password.

On PC and Android.
The .md are synchronized via nextcloud, can it have a link?

How can I recover my file?

Thank you for your help

**Comment by meld-cp** [comment]
Hi @sgab31,
Sorry, not much I can do.   Could the encoding between the markers (%%🔐 and 🔐%%) have changed at all?  If nextcloud (or some other backup) has versioning, you could try checking an earlier version and seeing if something between the markers have changed.   Just out of interest, have you changed devices at all since the note was encrypted?

**Comment by artstisen** [comment]
@sgab31,
Clicking and placing the caret in the encrypted string when opening the command palette is a bit risky as I can accidentally change the string. Instead I place the caret in the password hint section as this is just plain text.

I also copy just the encrypted string to another file for safekeeping in a "cipher index" which I link to from the original document.
![encrypt-decrypt](https://user-images.githubusercontent.com/46990511/197131024-28cd3364-44ab-48ac-afc1-dcbb32c3b8b9.png)

**Comment by sgab31** [comment]
> 

it doesn't matter.
I found a saved note and lost only few things.


For information, I didn't change device.
