### ISSUE TITLE
Encrypted notes should be aligned like the default Obsidian notes

### ISSUE THREAD

**Issue by meld-cp** [meld-cp/obsidian-encrypt#88]
The encrypted notes should be consistent, and follow the same alignment configuration as normal notes.

E.g. center of the editing space, as opposed to the far left.

This may be desktop only or more likely screen width dependent.  Check normal note CSS classes.

_Originally posted by @deusnovus in https://github.com/meld-cp/obsidian-encrypt/issues/48#issuecomment-1500895961_

**Comment by deusnovus** [comment]
My apologies, I meant to say margin! I don't know if it's intentional or not, but the difference in margin between normal notes and encrypted notes appears as so:

![example1](https://user-images.githubusercontent.com/32219080/230740260-38523640-9c1b-4f44-9f42-0cd62d687138.jpg)
![example2](https://user-images.githubusercontent.com/32219080/230740262-d43df069-f1aa-4421-a4f9-d7b1a1e6abe1.jpg)

It's a little bit different on iOS as well, but less noticeable.

**Comment by meld-cp** [comment]
Thanks for the screenshots.

The full width was intentional (only because I prefer my note taking that way) but I think it's better to follow the user preferences from the obsidian settings, so I'll aim to make it do that.

**Comment by meld-cp** [comment]
A note for me to make it follow the readable line length setting in Obsidian

![image](https://user-images.githubusercontent.com/18450687/230748026-5d71472c-15b9-434b-9651-848a3a8c1409.png)

**Comment by deusnovus** [comment]
Yeah, for the sake of uniformity, I think it's better for plugins to not have any personalized cosmetics that veer away from the user's default / custom CSS theme, but you can always add the option for full-width notes.

**Comment by meld-cp** [comment]
Fixed in v2.1.3
